"""initial_schema

Revision ID: 2ff7c045f96a
Revises: 
Create Date: 2026-07-05 17:45:32.745130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '2ff7c045f96a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('module', sa.Enum('SPEAKING', 'VOCABULARY', 'WRITING', name='achievementmodule'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_key'), 'achievements', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('oauth_provider', sa.Enum('GOOGLE', name='oauthprovider'), nullable=True),
    sa.Column('oauth_provider_id', sa.String(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('content_generation_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_type', sa.Enum('SPEAKING', 'VOCABULARY', 'WRITING', 'INTERVIEW_PANEL', name='contentgenerationmoduletype'), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'GENERATING', 'IN_REVIEW', 'PUBLISHED', name='contentgenerationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('speaking_done', sa.Boolean(), nullable=False),
    sa.Column('vocab_done', sa.Boolean(), nullable=False),
    sa.Column('writing_done', sa.Boolean(), nullable=False),
    sa.Column('total_practice_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_table('interview_panel_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Enum('SOFTWARE_TECH', 'BUSINESS_FINANCE', 'HEALTHCARE', 'SALES_MARKETING', 'CUSTOMER_SERVICE', 'ACADEMIC_RESEARCH', 'GENERAL', name='interviewdomain'), nullable=False),
    sa.Column('level', sa.Enum('ENTRY', 'MID', 'SENIOR', name='interviewlevel'), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company_style', sa.Enum('STARTUP', 'CORPORATE', name='companystyle'), nullable=True),
    sa.Column('interview_mode', sa.Enum('FULL_PANEL', 'SINGLE_AGENT', name='interviewmode'), nullable=False),
    sa.Column('selected_agent_type', sa.Enum('HR', 'TECHNICAL', 'MANAGER', name='agenttype'), nullable=True),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('session_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wildcards_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'ABANDONED', name='panelsessionstatus'), nullable=False),
    sa.Column('end_reason', sa.Enum('NATURAL', 'USER_TARGET_REACHED', 'HARD_CEILING_REACHED', name='panelendreason'), nullable=True),
    sa.Column('overall_verdict', sa.Enum('STRONG_HIRE', 'HIRE', 'MAYBE', 'NO_HIRE', name='overallverdict'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personalized_vocab_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('SPEAKING', 'WRITING', name='suggestionsourcetype'), nullable=False),
    sa.Column('source_submission_id', sa.UUID(), nullable=True),
    sa.Column('original_word', sa.String(), nullable=False),
    sa.Column('original_sentence', sa.Text(), nullable=False),
    sa.Column('suggested_word', sa.String(), nullable=False),
    sa.Column('rewritten_sentence', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SHOWN', 'ADDED_TO_QUEUE', 'DISMISSED', name='suggestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_table('user_learning_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_cycle', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('FLUENCY', 'BUSINESS', 'EXAM', 'TRAVEL', name='goal'), nullable=False),
    sa.Column('target_cefr_level', sa.String(), nullable=False),
    sa.Column('native_language', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('daily_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('domain_question_bank',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Enum('SOFTWARE_TECH', 'BUSINESS_FINANCE', 'HEALTHCARE', 'SALES_MARKETING', 'CUSTOMER_SERVICE', 'ACADEMIC_RESEARCH', 'GENERAL', name='interviewdomain'), nullable=False),
    sa.Column('level', sa.Enum('ENTRY', 'MID', 'SENIOR', name='interviewlevel'), nullable=False),
    sa.Column('agent_type', sa.Enum('HR', 'TECHNICAL', 'MANAGER', name='agenttype'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('sub_category', sa.String(), nullable=False),
    sa.Column('expected_answer_notes', sa.Text(), nullable=False),
    sa.Column('research_grounded', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'PUBLISHED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('generation_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_batch_id'], ['content_generation_batches.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('HR', 'TECHNICAL', 'MANAGER', name='agenttype'), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('questions_asked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_panel_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speaking_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CONVERSATIONAL', 'PUBLIC_SPEAKING', 'IMPROMPTU', name='speakingexercisetype'), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('target_cefr_level', sa.String(), nullable=False),
    sa.Column('goal_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topic_embedding', app.db.models.speaking.Vector(), nullable=True),
    sa.Column('generated_by', sa.Enum('AI', 'HUMAN', name='contentsource'), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'PUBLISHED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('generation_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_batch_id'], ['content_generation_batches.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_practice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_activity_id', sa.UUID(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('fill_blank_score', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('context_score', sa.Integer(), nullable=True),
    sa.Column('pronunciation_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_progress.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('pronunciation_ipa', sa.String(), nullable=True),
    sa.Column('pronunciation_audio_url', sa.String(), nullable=True),
    sa.Column('example_sentences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('antonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_tips', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('target_cefr_level', sa.String(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('word_embedding', app.db.models.vocabulary.Vector(), nullable=True),
    sa.Column('generated_by', sa.Enum('AI', 'HUMAN', name='contentsource'), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'PUBLISHED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('generation_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_batch_id'], ['content_generation_batches.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_words_word'), 'vocabulary_words', ['word'], unique=True)
    op.create_table('wildcard_question_bank',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('CLASSIC_CURVEBALL', 'BRAIN_TEASER', 'SELF_REFLECTION', 'PRESSURE_TEST', name='wildcardcategory'), nullable=False),
    sa.Column('suitable_agent_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_level', sa.Enum('ENTRY', 'MID', 'SENIOR', name='interviewlevel'), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'PUBLISHED', name='reviewstatus'), nullable=False),
    sa.Column('generation_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_batch_id'], ['content_generation_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DESCRIPTIVE', 'NARRATIVE', 'ARGUMENTATIVE', name='writingprompttype'), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('prompt_title', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('target_word_count', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('writing_tips', sa.Text(), nullable=True),
    sa.Column('sample_outline', sa.Text(), nullable=True),
    sa.Column('sensitivity_flagged', sa.Boolean(), nullable=False),
    sa.Column('prompt_embedding', app.db.models.writing.Vector(), nullable=True),
    sa.Column('generated_by', sa.Enum('AI', 'HUMAN', name='contentsource'), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'PUBLISHED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('generation_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_batch_id'], ['content_generation_batches.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('user_answer_transcript', sa.Text(), nullable=False),
    sa.Column('agent_reaction_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('is_wildcard', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['panel_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speaking_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('daily_activity_id', sa.UUID(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('words_per_minute', sa.Float(), nullable=True),
    sa.Column('pause_count', sa.Integer(), nullable=True),
    sa.Column('filler_words_count', sa.Integer(), nullable=True),
    sa.Column('filler_words_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fluency_score', sa.Integer(), nullable=True),
    sa.Column('grammar_score', sa.Integer(), nullable=True),
    sa.Column('vocabulary_score', sa.Integer(), nullable=True),
    sa.Column('pronunciation_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('grammar_corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vocabulary_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='submissionstatus'), nullable=False),
    sa.Column('processing_job_id', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_progress.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['speaking_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_vocabulary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LEARNING', 'REVIEWING', 'MASTERED', name='vocabwordstatus'), nullable=False),
    sa.Column('times_practiced', sa.Integer(), nullable=False),
    sa.Column('times_reviewed', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('learned_at', sa.DateTime(), nullable=False),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_exercise_bank',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('fill_blank_sentence', sa.Text(), nullable=False),
    sa.Column('fill_blank_correct_answer', sa.String(), nullable=False),
    sa.Column('match_definition_distractor_1', sa.Text(), nullable=False),
    sa.Column('match_definition_distractor_2', sa.Text(), nullable=False),
    sa.Column('match_definition_distractor_3', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('daily_activity_id', sa.UUID(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('grammar_score', sa.Integer(), nullable=True),
    sa.Column('structure_score', sa.Integer(), nullable=True),
    sa.Column('vocabulary_score', sa.Integer(), nullable=True),
    sa.Column('coherence_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='submissionstatus'), nullable=False),
    sa.Column('processing_job_id', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_progress.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['writing_prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('persona', sa.Enum('FRIENDLY_TUTOR', 'NATIVE_PEER', 'EXAMINER', 'INTERVIEWER', name='livesessionpersona'), nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_seconds', sa.Float(), nullable=True),
    sa.Column('avg_response_length_words', sa.Float(), nullable=True),
    sa.Column('topic_relevance_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'TIMED_OUT', 'ERROR', name='livesessionstatus'), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('ephemeral_token_issued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['speaking_submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_agent_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('HR', 'TECHNICAL', 'MANAGER', 'SUMMARY', name='panelagentfeedbacktype'), nullable=False),
    sa.Column('score_contribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verdict_notes', sa.Text(), nullable=False),
    sa.Column('best_answer_reference', sa.UUID(), nullable=True),
    sa.Column('weakest_answer_reference', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['best_answer_reference'], ['panel_responses.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_panel_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weakest_answer_reference'], ['panel_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_submission_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('grammar_score', sa.Integer(), nullable=True),
    sa.Column('structure_score', sa.Integer(), nullable=True),
    sa.Column('vocabulary_score', sa.Integer(), nullable=True),
    sa.Column('coherence_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fixed_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['writing_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writing_submission_versions')
    op.drop_table('panel_agent_feedbacks')
    op.drop_table('live_conversation_sessions')
    op.drop_table('writing_submissions')
    op.drop_table('vocabulary_exercise_bank')
    op.drop_table('user_vocabulary')
    op.drop_table('speaking_submissions')
    op.drop_table('panel_responses')
    op.drop_table('writing_prompts')
    op.drop_table('wildcard_question_bank')
    op.drop_index(op.f('ix_vocabulary_words_word'), table_name='vocabulary_words')
    op.drop_table('vocabulary_words')
    op.drop_table('vocabulary_practice_sessions')
    op.drop_table('speaking_exercises')
    op.drop_table('panel_rounds')
    op.drop_table('domain_question_bank')
    op.drop_table('user_learning_profiles')
    op.drop_table('user_achievements')
    op.drop_table('personalized_vocab_suggestions')
    op.drop_table('interview_panel_sessions')
    op.drop_table('daily_progress')
    op.drop_table('content_generation_batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_achievements_key'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
